language: java
notifications:
  email: false
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build test
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)