language: java
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)